services:
  - type: web
    name: aura-programming-language
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python aura_web.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production